Dev
4esa/crave pull request #1
Opened 2019-07-08 13:41 UTC by joss0

Some important fixes and small refactoring

2019-07-08 22:13 UTC, scottanglr requested changes
Changes look good. It's worth noting that the introduction of arrow functions reduce browser support, but this shouldn't be an issue.

Couple of notes:
- Why use HEX code instead of RGB for colouring the feedback text?
- randomColor appears to no longer be used, but the code was updated
- It's definitely moved into a more functional paradigm. However it doesn't necessarily match up with the rest of the code, and might not be easier to read for humans. What do you think?

2019-07-09 03:16 UTC, joss0 reviewed
> might not be easier to read for humans

While this might be true for the randomColor function, I think it makes an important point as to how I think about programming.

I think programming should be thought of as receiving data from somewhere, changing the data somehow, then sending the data somewhere.

I can't but barely read your functions because they don't return anything and I can't test any part by its self. You look at my [codepen](https://codepen.io/Jahjs/pen/RzYmQx) I made for this project to see if I could work out how it works and you see the first thing I did was paste in the createTable function. I immediately realised there was no way of testing any of the logic in the function without completely dissecting it. So I wrote the randomColor function, quickly got distracted by array destructuring with the cool vect functions I made 😛.

2019-07-09 03:16 UTC, joss0 commented on public/js/index.js
> +
Oh! I changed the functionality to demonstrate how it would work and and also see that it worked, but I can change the functionality back.

2019-07-09 04:01 UTC, joss0 commented on public/js/index.js
> +
There is a bug where if the leading hex digits from `Math.random() * parseInt("FFFFFF", 16)` are zero the hex colour will be wrong

2019-08-22 00:43 UTC, merged